version: "3.5"
networks:
  benchmarking-fw-net:
    external : true
    name: ${TESTNET:-benchmarking-fw-net}

volumes:
  grafana-data:
    external : true
    name: ${GF_DATA_VOL_NAME:-testnet_grafana_data}
  influxdb-data:
    external : true
    name: ${INFLUXDB_VOL_NAME:-testnet_influxdb_data}
  prometheus-data:
    external : true
    name: ${PROM_DATA_VOL_NAME:-testnet_prometheus_data}

services:
  influxdb:
    image: influxdb:1.8.1
    container_name: influxdb
    environment:
      - INFLUXDB_ADMIN_ENABLED=true 
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER:-admin}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-admin}
      - INFLUXDB_DB="bbf-monitoring-db"
      - INFLUXDB_HTTP_LOG_ENABLED=false
      - INFLUXDB_REPORTING_DISABLED=true
      - INFLUXDB_USER=${INFLUXDB_USER:-iff_user}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD:-iff_psw}
    networks:
      - benchmarking-fw-net
    volumes:
      - influxdb-data:/var/lib/influxdb
    ports:
      - 8086:8086
  pushgateway:
    image: prom/pushgateway:${PUSHGW_IMG_TAG:-latest}
    container_name: pushgateway
    ports:
      - 9091:9091
    networks:
      - benchmarking-fw-net
  prometheus:
    image: prom/prometheus:v2.0.0
    container_name: prometheus
    command: --config.file=/etc/prometheus/prometheus.yml
    networks:
      - benchmarking-fw-net
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alerts/:/etc/prometheus/rules.d/
      - prometheus-data:/prometheus/data
  grafana:
    image: grafana/grafana:${GRAFANA_IMG_TAG:-latest}
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - benchmarking-fw-net
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - grafana-data:/var/lib/grafana
  statsd:
    image: graphiteapp/graphite-statsd
    container_name: statsdgraphite
    networks:
      - benchmarking-fw-net
    ports:
      - 81:80
      - 8126:8126
      - 8125:8125/udp    
  alertmanager:
    image: prom/alertmanager:${ALERTMANAGER_IMG_TAG:-latest}
    container_name: alertmanager
    command: --config.file=/etc/alertmanager/alertmanager.yml
    networks:
      - benchmarking-fw-net
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
  docker_stats_exporter:
    image: wywywywy/docker_stats_exporter:latest
    container_name: dc_stats_exp
    ports:
      - 9487:9487
    networks: 
      - benchmarking-fw-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  dozzle:
    container_name: containers_logs_ui
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8888:8080
    networks: 
      - benchmarking-fw-net

